AWSTemplateFormatVersion: 2010-09-09
Globals:
  Function:
    Environment:
      Variables:
        SIGNUPS_TABLE_NAME:
          Ref: SignupsTable
        STAGE_NAME:
          Ref: Environment
Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
Resources:
  PostSignup:
    Properties:
      CodeUri: s3://dynamodb-data-logger-web-hook/f71c8a0262ed79edb823c40899d4da42
      Events:
        GetEvent:
          Properties:
            Method: post
            Path: /signups
          Type: Api
      Handler: signups.post
      Policies:
      - AWSLambdaExecute
      - AmazonDynamoDBFullAccess
      Runtime: ruby2.5
    Type: AWS::Serverless::Function
  S3AssetsBucket:
    Properties:
      AccessControl: PublicRead
      BucketName:
        Fn::Sub: ${Environment}.assets.${ProjectName}
    Type: AWS::S3::Bucket
  SignupsTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: created_at
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: created_at
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName:
        Fn::Join:
        - '-'
        - - Ref: ProjectName
          - Ref: Environment
    Type: AWS::DynamoDB::Table
Transform:
- AWS::Serverless-2016-10-31
